config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  devise_for :users
    
  # get '/users/sign_out' to: 'devise/sessions#destroy'
  

  resources :trips do
    resources :locations
  end

  resources :locations do
    resources :addresses
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :location
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip
  has_one :address, dependent: :destroy
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :locations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips, dependent: :destroy
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_location
  before_action :set_trip
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  def index
  end

  def show
  end

  def new
    @address = Address.new()
  end

  def create
    @address = @location.address.new(address_params)
    if @address.save
      redirect_to trip_location_path(@trip,@location)
    else
      render :new
    end
  end



  def edit
  end

  def update
    if @address.update(address_params)
      redirect_to trip_location_path(@trip,@location)
    else
      render :edit
    end
  end

  def destroy
    @address.destroy
    Address.create(street:"", city:"", state:"", zipcode: nil , location_id: @location.id)
    redirect_to trip_location_path(@trip,@location)

  end

  private

  def set_address
    @address = @location.address
  end

  def set_location
    @location = Location.find(params[:location_id])
  end

  def set_trip
    @trip = @location.trip
  end

  def address_params
    params.require(:address).permit(:street, :city, :state, :zipcode)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_trip
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
    @location = Location.new
  end

  def create
    @location = @trip.locations.new(location_params)
    if @location.save
      Address.create(street:"", city:"", state:"", zipcode: nil , location_id: @location.id)
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @location.update(location_params)
      redirect_to trip_path(@trip)
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to trip_path(@trip)
  end


  private

  def location_params
    params.require(:location).permit(:name, :attraction)
  end

  def set_location
    @location = @trip.locations.find(params[:id])
  end

  def set_trip
    @trip = current_user.trips.find(params[:trip_id])
  end

  def set_address
    @address = @location.address
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = current_user.trips
  end

  def show
    @locations = @trip.locations

  end

  def new
    @trip = Trip.new()
  end

  def create
    @trip = current_user.trips.new(trip_params)
    if @trip.save
      redirect_to trips_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to trip_path(@trip)
    else
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private

  def trip_params
    params.require(:trip).permit(:title, :date, :description)
  end

  def set_trip
    @trip = current_user.trips.find(params[:id])
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/edit.html.erb
<h1>Editing <%=@location.name%> Address</h1>

<%=form_for [@location, @address] do |f|%>
  <%= f.label :street %>
  <%= f.text_field :street%>

  <%= f.label :city %>
  <%= f.text_field :city %>
  
  <%= f.label :state%>
  <%= f.text_field :state %>
  
  <%= f.label :zipcode %>
  <%= f.text_field :zipcode %>

  <%= f.submit %>
  <% end %>

app/views/addresses/index.html.erb
<h1>Addresses#index</h1>
<p>Find me in app/views/addresses/index.html.erb</p>

app/views/addresses/new.html.erb
<h1>New Address for <%=@location.name%></h1>

<%=form_for @address do |f|%>
  <%= f.label :street %>
  <%= f.text_field :street%>

  <%= f.label :city %>
  <%= f.text_field :city %>
  
  <%= f.label :state%>
  <%= f.text_field :state %>
  
  <%= f.label :zipcode %>
  <%= f.text_field :zipcode %>

  <%= f.submit %>
  <% end %>

app/views/addresses/show.html.erb
<h1>Addresses#show</h1>
<p>Find me in app/views/addresses/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackprac</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
   <div class="container">
      
      <p>
      <%= link_to "Home", root_path, :class => "waves-effect waves-light btn"%>
      <%= link_to "Login", new_user_session_path, :class => "waves-effect waves-light btn"%>
      <%=link_to "LogOut", destroy_user_session_path, :method => :delete , :class => "waves-effect waves-light btn"%>
      <%= link_to "Sign Up", new_user_registration_path, :class => "waves-effect waves-light btn"%>
      <%= link_to "View Trips", trips_path, :class => "waves-effect waves-light btn"%></p>

 
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/locations/edit.html.erb
<h1>Editing <%=@location.name%></h1>

<%=form_for [@trip,@location] do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :attraction %>
  <%= f.text_field :attraction %>

  <%= f.submit %>
  <% end %>

app/views/locations/index.html.erb
<h1>Locations#index</h1>
<p>Find me in app/views/locations/index.html.erb</p>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%=form_for [@trip, @location] do |f|%>
  <%= f.label :name%>
  <%= f.text_field :name%>

  <%= f.label :attraction%>
  <%= f.text_field :attraction%>

  <%= f.submit %>
  <% end %>

app/views/locations/show.html.erb
<h1>Location</h1>
<%=link_to "Back to Trip Locations", trip_path(@trip)%>
<h3><%=@location.name%></h3>

<p><%= link_to "Edit", edit_trip_location_path(@trip, @location), :class => "waves-effect waves-light btn" %>
<%= link_to "Delete", trip_location_path(@trip, @location), method: :delete, :class => "waves-effect waves-light btn" %></p>

<h3>Address</h3>
<p>Address: <%=@address.street%></p>
<p>City: <%=@address.city%></p>
<p>State: <%=@address.state%></p>
<p>Zip: <%=@address.zipcode%></p>

<p><%= link_to "New/Edit", edit_location_address_path(@location, @address), :class => "waves-effect waves-light btn" %>
<%= link_to "Delete", location_address_path(@location, @address), method: :delete, :class => "waves-effect waves-light btn" %></p>

app/views/trips/edit.html.erb
<h1>Editing <%=@trip.title%></h1>

<%=form_for @trip do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :date %>
  <%= f.date_field :date, "data-provide" => 'datepicker'%>
  
  <%= f.submit %>
  <% end %>

app/views/trips/index.html.erb
<h1>Welcome <%=current_user.first_name%>!</h1>

<%= link_to "Start a new Trip!", new_trip_path , :class => "waves-effect waves-light btn"%>
<p>Below are all of your trips</p>
<% @trips.each do |trip|%>
<p>
<%= link_to trip.title, trip_path(trip) %>
</p>
<% end %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%=form_for @trip do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :date %>
  <%= f.date_field :date, "data-provide" => 'datepicker'%>
  
  <a class = "waves-effect waves-light btn" ><%= f.submit %></a>
  <% end %>

app/views/trips/show.html.erb
<h1><%=@trip.title%></h1>
<h4><%=@trip.date.strftime("%m-%d-%y")%></h4>
<%=link_to "Back to Trips", trips_path%>

<p><%= link_to "Edit", edit_trip_path(@trip), :class => "waves-effect waves-light btn"%>
<%= link_to "Delete", trip_path(@trip), method: :delete, :class => "waves-effect waves-light btn" %></p>

<h3>Here is a list of all the locations in your trip!</h3>
<p><%= link_to "New", new_trip_location_path(@trip), :class => "waves-effect waves-light btn" %></p>
<%@locations.each do |location|%>
<p>
<%=link_to location.name, trip_location_path(@trip,location)%>
</p>
<% end %>